# Use an official Node.js runtime as a parent image
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy application code
COPY . .

# Install app dependencies
RUN npm install

# Expose the port the app runs on
EXPOSE 3000
ENV PORT=3000

# Define the command to run the app
CMD ["node", "./node_modules/y-webrtc/bin/server.js"]